[phases.setup]
nixpkgs = ["nodejs_18", "python3", "gcc", "gnumake"]

[phases.install]
cmds = [
  "cp package.railway.json package.json",
  "npm ci --only=production"
]

[variables]
NODE_ENV = "production"

[start]
cmd = "node server.js" 